app/routes.py
from flask import request, jsonify, Blueprint, render_template, redirect, url_for, flash, current_app
from flask_login import login_user, logout_user, login_required, current_user
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from .models import User, Incident
from .forms import RegistrationForm, LoginForm, IncidentForm
from datetime import datetime

# Crear un Blueprint para las rutas principales
main = Blueprint('main', __name__)

# Ruta para la página principal
@main.route('/')
@main.route('/index')
@login_required
def index():
    nombre_usuario = current_user.username
    return render_template('index.html', nombre_usuario=nombre_usuario)

# Ruta para el dashboard
@main.route('/dashboard', methods=['GET', 'POST'])
@login_required
def dashboard():
    if request.method == 'POST':
        delete_id = request.form.get('delete_id')
        if delete_id:
            incident_to_delete = Incident.query.get(delete_id)
            if incident_to_delete:
                db.session.delete(incident_to_delete)
                db.session.commit()
                flash('Incident deleted successfully.', 'success')
            else:
                flash('Incident not found.', 'danger')
        return redirect(url_for('main.dashboard'))

    project_filter = request.args.get('project', '')
    responsible_filter = request.args.get('responsible', '')
    status_filter = request.args.get('status', '')
    
    query = Incident.query
    
    if project_filter:
        query = query.filter_by(project=project_filter)
    if responsible_filter:
        query = query.filter_by(responsible=responsible_filter)
    if status_filter:
        query = query.filter_by(status=status_filter)
    
    incidents = query.all()
    return render_template('dashboard.html', incidents=incidents)

# Ruta para el registro de usuarios
@main.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        new_user = User(username=form.username.data, email=form.email.data)
        new_user.set_password(form.password.data)
        db.session.add(new_user)
        db.session.commit()
        
        # Iniciar sesión automáticamente después del registro
        login_user(new_user)
        flash('Account created and logged in successfully.', 'success')
        return redirect(url_for('main.profile'))  # Redirigir al perfil en lugar de la página de inicio
    return render_template('register.html', form=form)

# Ruta para el inicio de sesión
@main.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is None or not user.check_password(form.password.data):
            flash('Invalid email or password')
            return redirect(url_for('main.login'))
        login_user(user, remember=form.remember_me.data)
        return redirect(url_for('main.profile'))
    return render_template('login.html', title='Sign In', form=form)

# Ruta para el perfil del usuario
@main.route('/profile')
@login_required
def profile():
    return render_template('profile.html', name=current_user.username)

# Ruta para cerrar sesión
@main.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.login'))

# Ruta para registrar un incidente
@main.route('/register_incident', methods=['GET', 'POST'])
@login_required
def register_incident():
    if request.method == 'POST':
        project = request.form.get('project')
        description = request.form.get('description')
        position = request.form.get('position')
        responsible = request.form.get('responsible')
        status = request.form.get('status')
        created_by = current_user.username

        new_incident = Incident(
            project=project,
            description=description,
            position=position,
            responsible=responsible,
            status=status,
            created_by=created_by,
            created_at=datetime.utcnow()
        )
        db.session.add(new_incident)
        db.session.commit()
        flash('Incident registered successfully.', 'success')
        return redirect(url_for('main.dashboard'))

    form = IncidentForm()
    return render_template('register_incident.html', form=form)

# Ruta para cerrar un incidente
@main.route('/close_incident/<int:incident_id>', methods=['POST'])
@login_required
def close_incident(incident_id):
    incident = Incident.query.get(incident_id)
    if incident:
        incident.status = 'Cerrado'
        db.session.commit()
        flash('Incident closed successfully.', 'success')
    else:
        flash('Incident not found.', 'danger')
    return redirect(url_for('main.dashboard'))

# Ruta para reabrir un incidente
@main.route('/reopen_incident/<int:incident_id>', methods=['POST'])
@login_required
def reopen_incident(incident_id):
    incident = Incident.query.get(incident_id)
    if incident:
        incident.status = 'Abierto'
        db.session.commit()
        flash('Incident reopened successfully.', 'success')
    else:
        flash('Incident not found.', 'danger')
    return redirect(url_for('main.dashboard'))

# Ruta para mostrar los KPIs
@main.route('/kpis')
@login_required
def kpis():
    incidents = Incident.query.all()
    incidents_dict = [incident.to_dict() for incident in incidents]
    return render_template('KPI.html', incidents=incidents_dict)

# Ruta para gestionar usuarios
@main.route('/manage_users')
@login_required
def manage_users():
    users = User.query.all()
    return render_template('admin_users.html', users=users)

app/templates/KPI.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>KPIs</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='kpi.css') }}">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <style>
        .chart-container {
            position: relative;
            width: 100%;
            height: 500px;
        }
        .legend-container {
            display: flex;
            flex-wrap: wrap;
            justify-content: center;
            margin-top: 20px;
        }
        .legend-item {
            display: flex;
            align-items: center;
            margin: 5px;
        }
        .legend-color-box {
            width: 20px;
            height: 20px;
            display: inline-block;
            margin-right: 10px;
        }
    </style>
</head>
<body class="kpi">
    <div class="header">
        <div class="nav-buttons">
            <a href="{{ url_for('main.index') }}" class="button">Home</a>
            <a href="{{ url_for('main.dashboard') }}" class="button">Dashboard</a>
            <a href="{{ url_for('main.register_incident') }}" class="button">Registrar Incidencia</a>
            <a href="{{ url_for('main.logout') }}" class="button logout">Logout</a>
        </div>
    </div>
    <div class="container">
        <div class="filter-container">
            <form method="GET" action="{{ url_for('main.kpis') }}" class="filter-form">
                <div class="filter-group">
                    <label for="project">Proyecto:</label>
                    <select name="project" id="project" class="form-control">
                        <option value="">TODOS</option>
                        <option value="Madrid_T7" {% if request.args.get('project') == 'Madrid_T7' %}selected{% endif %}>Madrid_T7</option>
                        <option value="Luxemburgo_T1" {% if request.args.get('project') == 'Luxemburgo_T1' %}selected{% endif %}>Luxemburgo_T1</option>
                        <option value="Brujas_T1" {% if request.args.get('project') == 'Brujas_T1' %}selected{% endif %}>Brujas_T1</option>
                        <option value="Estocolmo_T2" {% if request.args.get('project') == 'Estocolmo_T2' %}selected{% endif %}>Estocolmo_T2</option>
                        <option value="Paris_T6" {% if request.args.get('project') == 'Paris_T6' %}selected{% endif %}>Paris_T6</option>
                        <option value="Lisboa_T4" {% if request.args.get('project') == 'Lisboa_T4' %}selected{% endif %}>Lisboa_T4</option>
                        <option value="Roma_T2" {% if request.args.get('project') == 'Roma_T2' %}selected{% endif %}>Roma_T2</option>
                        <option value="Munich_T2" {% if request.args.get('project') == 'Munich_T2' %}selected{% endif %}>Munich_T2</option>
                        <option value="London_T2" {% if request.args.get('project') == 'London_T2' %}selected{% endif %}>London_T2</option>
                    </select>
                </div>
                <button type="submit" class="dashboard-button">Filter</button>
            </form>
        </div>
        <div class="row">
            <div class="box">
                <h2>Incidencias por Proyecto</h2>
                <div class="chart-container">
                    <canvas id="incidenciasProyectoChart"></canvas>
                </div>
            </div>
            <div class="box">
                <h2>Estado de las Incidencias</h2>
                <div class="chart-container">
                    <canvas id="estadoIncidenciasChart"></canvas>
                </div>
            </div>
            <div class="box">
                <h2>Incidencias por Responsable</h2>
                <div class="chart-container">
                    <canvas id="responsableIncidenciasChart"></canvas>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="box">
                <h2>Histórico de Incidencias</h2>
                <div class="chart-container">
                    <canvas id="historicoIncidenciasChart"></canvas>
                </div>
            </div>
            <div class="box">
                <h2>Incidencias por Proyecto y Mes</h2>
                <div class="chart-container">
                    <canvas id="incidenciasPorProyectoYMesChart"></canvas>
                </div>
                <div id="project-legend" class="legend-container"></div>
            </div>
            <div class="box">
                <h2>Incidencias por Autor</h2>
                <div class="chart-container">
                    <canvas id="incidenciasAutorChart"></canvas>
                </div>
            </div>
        </div>
    </div>
    <script>
        const incidents = {{ incidents|tojson|safe }};
        const colors = [
            'rgba(75, 192, 192, 0.6)',
            'rgba(255, 99, 132, 0.6)',
            'rgba(54, 162, 235, 0.6)',
            'rgba(255, 206, 86, 0.6)',
            'rgba(153, 102, 255, 0.6)',
            'rgba(255, 159, 64, 0.6)',
            'rgba(75, 192, 192, 0.4)',
            'rgba(255, 99, 132, 0.4)',
            'rgba(54, 162, 235, 0.4)',
            'rgba(255, 206, 86, 0.4)',
            'rgba(153, 102, 255, 0.4)',
            'rgba(255, 159, 64, 0.4)'
        ];

        function filterIncidents(incidents, project) {
            if (!project) {
                return incidents;
            }
            return incidents.filter(incident => incident.project === project);
        }

        function updateCharts() {
            const project = document.getElementById('project').value;
            const filteredIncidents = filterIncidents(incidents, project);

            // Data preparation for the charts
            const projectCounts = {};
            const statusCounts = { "Abierto": 0, "Cerrado": 0 };
            const responsibleCounts = {};
            const monthlyCounts = new Array(12).fill(0);
            const projectMonthlyCounts = {};
            const authorCounts = {};

            filteredIncidents.forEach(incident => {
                // Incidencias por Proyecto
                projectCounts[incident.project] = (projectCounts[incident.project] || 0) + 1;

                // Estado de las Incidencias
                statusCounts[incident.status] = (statusCounts[incident.status] || 0) + 1;

                // Incidencias por Responsable
                responsibleCounts[incident.responsible] = (responsibleCounts[incident.responsible] || 0) + 1;

                // Histórico de Incidencias
                const createdAt = new Date(incident.created_at);
                monthlyCounts[createdAt.getMonth()]++;

                // Incidencias por Proyecto y Mes
                if (!projectMonthlyCounts[incident.project]) {
                    projectMonthlyCounts[incident.project] = new Array(12).fill(0);
                }
                projectMonthlyCounts[incident.project][createdAt.getMonth()]++;

                // Incidencias por Autor
                authorCounts[incident.created_by] = (authorCounts[incident.created_by] || 0) + 1;
            });

            // Incidencias por Proyecto Chart
            new Chart(document.getElementById('incidenciasProyectoChart'), {
                type: 'bar',
                data: {
                    labels: Object.keys(projectCounts),
                    datasets: [{
                        label: 'Incidencias por Proyecto',
                        data: Object.values(projectCounts),
                        backgroundColor: colors.slice(0, Object.keys(projectCounts).length),
                        borderColor: colors.slice(0, Object.keys(projectCounts).length).map(color => color.replace('0.6', '1')),
                        borderWidth: 1
                    }]
                },
                options: {
                    responsive: true,
                    maintainAspectRatio: true
                }
            });

            // Estado de las Incidencias Chart
            new Chart(document.getElementById('estadoIncidenciasChart'), {
                type: 'pie',
                data: {
                    labels: Object.keys(statusCounts),
                    datasets: [{
                        label: 'Estado de las Incidencias',
                        data: Object.values(statusCounts),
                        backgroundColor: ['rgba(255, 99, 132, 0.2)', 'rgba(54, 162, 235, 0.2)'],
                        borderColor: ['rgba(255, 99, 132, 1)', 'rgba(54, 162, 235, 1)'],
                        borderWidth: 1
                    }]
                },
                options: {
                    responsive: true,
                    maintainAspectRatio: true
                }
            });

            // Incidencias por Responsable Chart
            new Chart(document.getElementById('responsableIncidenciasChart'), {
                type: 'bar',
                data: {
                    labels: Object.keys(responsibleCounts),
                    datasets: [{
                        label: 'Incidencias por Responsable',
                        data: Object.values(responsibleCounts),
                        backgroundColor: 'rgba(153, 102, 255, 0.2)',
                        borderColor: 'rgba(153, 102, 255, 1)',
                        borderWidth: 1
                    }]
                },
                options: {
                    responsive: true,
                    maintainAspectRatio: true
                }
            });

            // Histórico de Incidencias Chart
            new Chart(document.getElementById('historicoIncidenciasChart'), {
                type: 'line',
                data: {
                    labels: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
                    datasets: [{
                        label: 'Histórico de Incidencias',
                        data: monthlyCounts,
                        backgroundColor: 'rgba(255, 206, 86, 0.2)',
                        borderColor: 'rgba(255, 206, 86, 1)',
                        borderWidth: 1
                    }]
                },
                options: {
                    responsive: true,
                    maintainAspectRatio: true
                }
            });

            // Incidencias por Proyecto y Mes Chart
            const datasets = Object.keys(projectMonthlyCounts).map((project, index) => ({
                label: project,
                data: projectMonthlyCounts[project],
                borderColor: colors[index % colors.length],
                backgroundColor: colors[index % colors.length].replace('1)', '0.2)'),
                fill: false
            }));

            new Chart(document.getElementById('incidenciasPorProyectoYMesChart'), {
                type: 'line',
                data: {
                    labels: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
                    datasets: datasets
                },
                options: {
                    responsive: true,
                    maintainAspectRatio: true,
                    legend: {
                        display: false // Oculta la leyenda del gráfico
                    }
                }
            });

            // Crear leyenda personalizada debajo del gráfico
            const legendContainer = document.getElementById('project-legend');
            legendContainer.innerHTML = ''; // Limpiar leyenda anterior

            datasets.forEach((dataset, index) => {
                const legendItem = document.createElement('div');
                legendItem.className = 'legend-item';

                const colorBox = document.createElement('span');
                colorBox.className = 'legend-color-box';
                colorBox.style.backgroundColor = colors[index % colors.length].replace('1)', '0.6)');

                const text = document.createElement('span');
                text.innerText = dataset.label;

                legendItem.appendChild(colorBox);
                legendItem.appendChild(text);
                legendContainer.appendChild(legendItem);
            });

            // Incidencias por Autor Chart
            new Chart(document.getElementById('incidenciasAutorChart'), {
                type: 'bar',
                data: {
                    labels: Object.keys(authorCounts),
                    datasets: [{
                        label: 'Incidencias por Autor',
                        data: Object.values(authorCounts),
                        backgroundColor: 'rgba(75, 192, 192, 0.2)',
                        borderColor: 'rgba(75, 192, 192, 1)',
                        borderWidth: 1
                    }]
                },
                options: {
                    responsive: true,
                    maintainAspectRatio: true
                }
            });
        }

        document.getElementById('project').addEventListener('change', updateCharts);
        updateCharts();
    </script>
</body>
</html>

app/templates/admin_users.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Users</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    <div class="container">
        <h1>Admin - User Management</h1>
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Username</th>
                    <th>Email</th>
                    <th>Admin</th>
                </tr>
            </thead>
            <tbody>
                {% for user in users %}
                <tr>
                    <td>{{ user.id }}</td>
                    <td>{{ user.username }}</td>
                    <td>{{ user.email }}</td>
                    <td>{{ user.is_admin }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</body>
</html>

app/templates/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Incidencias</title>
    <!-- Vinculación del archivo de estilos CSS para la página del dashboard -->
    <link rel="stylesheet" href="{{ url_for('static', filename='dashboard.css') }}">
</head>
<body class="dashboard">
    <div class="dashboard-container">
        <!-- Encabezado del dashboard -->
        <div class="dashboard-header">
            <h1>Incidencias</h1>
            <div class="header-links">
                <!-- Enlaces de navegación para las diferentes secciones de la aplicación -->
                <a href="{{ url_for('main.index') }}" class="header-link">Home</a>
                <a href="{{ url_for('main.kpis') }}" class="header-link">KPIs</a>
                <a href="{{ url_for('main.register_incident') }}" class="header-link">Registrar Incidencia</a>
                <a href="{{ url_for('main.logout') }}" class="header-link logout-link">Logout</a>
            </div>
        </div>
        <div class="dashboard-content">
            <!-- Formulario para filtrar incidencias -->
            <form method="GET" action="{{ url_for('main.dashboard') }}" class="filter-form">
                <div class="filter-container">
                    <!-- Campo de selección para filtrar por proyecto -->
                    <label for="project">Proyecto:</label>
                    <select name="project" id="project" class="form-control">
                        <option value="">TODOS</option>
                        <!-- Lista de opciones para proyectos -->
                        <option value="Madrid_T7" {% if request.args.get('project') == 'Madrid_T7' %}selected{% endif %}>Madrid_T7</option>
                        <option value="Luxemburgo_T1" {% if request.args.get('project') == 'Luxemburgo_T1' %}selected{% endif %}>Luxemburgo_T1</option>
                        <option value="Brujas_T1" {% if request.args.get('project') == 'Brujas_T1' %}selected{% endif %}>Brujas_T1</option>
                        <option value="Estocolmo_T2" {% if request.args.get('project') == 'Estocolmo_T2' %}selected{% endif %}>Estocolmo_T2</option>
                        <option value="Paris_T6" {% if request.args.get('project') == 'Paris_T6' %}selected{% endif %}>Paris_T6</option>
                        <option value="Lisboa_T4" {% if request.args.get('project') == 'Lisboa_T4' %}selected{% endif %}>Lisboa_T4</option>
                        <option value="Roma_T2" {% if request.args.get('project') == 'Roma_T2' %}selected{% endif %}>Roma_T2</option>
                        <option value="Munich_T2" {% if request.args.get('project') == 'Munich_T2' %}selected{% endif %}>Munich_T2</option>
                        <option value="London_T2" {% if request.args.get('project') == 'London_T2' %}selected{% endif %}>London_T2</option>
                    </select>
                    
                    <!-- Campo de selección para filtrar por responsable -->
                    <label for="responsible">Responsable:</label>
                    <select name="responsible" id="responsible" class="form-control">
                        <option value="">TODOS</option>
                        <!-- Lista de opciones para responsables -->
                        <option value="Electrico" {% if request.args.get('responsible') == 'Electrico' %}selected{% endif %}>Electrico</option>
                        <option value="Mecanico" {% if request.args.get('responsible') == 'Mecanico' %}selected{% endif %}>Mecanico</option>
                        <option value="Calidad" {% if request.args.get('responsible') == 'Calidad' %}selected{% endif %}>Calidad</option>
                        <option value="Aprovisionamientos" {% if request.args.get('responsible') == 'Aprovisionamientos' %}selected{% endif %}>Aprovisionamientos</option>
                        <option value="IT" {% if request.args.get('responsible') == 'IT' %}selected{% endif %}>IT</option>
                    </select>
                    
                    <!-- Campo de selección para filtrar por estado -->
                    <label for="status">Estado:</label>
                    <select name="status" id="status" class="form-control">
                        <option value="">TODOS</option>
                        <!-- Lista de opciones para estado -->
                        <option value="Abierto" {% if request.args.get('status') == 'Abierto' %}selected{% endif %}>Abierto</option>
                        <option value="Cerrado" {% if request.args.get('status') == 'Cerrado' %}selected{% endif %}>Cerrado</option>
                    </select>
                    
                    <!-- Botón para aplicar los filtros -->
                    <button type="submit" class="dashboard-button">Filtrar</button>
                </div>
            </form>

            <!-- Formulario para eliminar una incidencia -->
            <form method="POST" action="{{ url_for('main.dashboard') }}">
                <div class="delete-container">
                    <label for="delete_id">ID de la Incidencia a eliminar:</label>
                    <div class="delete-input-group">
                        <input type="text" name="delete_id" id="delete_id" placeholder="Enter incident ID" class="form-control delete-input">
                        <button type="submit" class="dashboard-button delete-button">Eliminar Incidencia</button>
                    </div>
                </div>
            </form>

            <!-- Tabla de incidencias -->
            <div class="table-container">
                <h2>Todas las Incidencias</h2>
                <table id="incidents-table">
                    <thead>
                        <tr>
                            <!-- Encabezados de la tabla -->
                            <th>ID</th>
                            <th>Proyecto</th>
                            <th>Descripción</th>
                            <th>Posición</th>
                            <th>Responsable</th>
                            <th>Estado</th>
                            <th>Creado por</th>
                            <th>Fecha de Creación</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        <!-- Iteración sobre las incidencias para poblar la tabla -->
                        {% for incident in incidents %}
                        <tr>
                            <td>{{ incident.id }}</td>
                            <td>{{ incident.project }}</td>
                            <td>{{ incident.description }}</td>
                            <td>{{ incident.position }}</td>
                            <td>{{ incident.responsible }}</td>
                            <td>{{ incident.status }}</td>
                            <td>{{ incident.created_by }}</td>
                            <td>{{ incident.created_at.strftime('%Y-%m-%d') }}</td>
                            <td>
                                <!-- Acciones para cerrar o reabrir la incidencia -->
                                {% if incident.status == 'Abierto' %}
                                <form method="POST" action="{{ url_for('main.close_incident', incident_id=incident.id) }}">
                                    <button type="submit" class="dashboard-button close-button">Cerrar</button>
                                </form>
                                {% elif incident.status == 'Cerrado' %}
                                <form method="POST" action="{{ url_for('main.reopen_incident', incident_id=incident.id) }}">
                                    <button type="submit" class="dashboard-button reopen-button">Reabrir</button>
                                </form>
                                {% endif %}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</body>
</html>

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bienvenido</title>
    <!-- Vinculación del archivo de estilos CSS para la página de inicio -->
    <link rel="stylesheet" href="{{ url_for('static', filename='index.css') }}">
</head>
<body class="index">
    <div class="index-container">
        <!-- Encabezado de la página de inicio -->
        <div class="index-header">
            <h1>Bienvenido {{ nombre_usuario|capitalize }}, Sistema de Gestión de Incidencias.</h1>
        </div>
        <!-- Enlace para cerrar sesión -->
        <div class="header-links">
            <a href="{{ url_for('main.logout') }}" class="button btn-logout">Logout</a>
        </div>
        <!-- Contenido principal de la página de inicio -->
        <div class="index-content">
            <h3>Navega a través de nuestras herramientas para gestionar y analizar las incidencias de tu proyecto.</h3>
            <!-- Contenedor de las herramientas disponibles -->
            <div class="tool-boxes">
                <!-- Caja de herramienta del Dashboard -->
                <div class="tool-box">
                    <nav>
                        <!-- Enlace para gestionar usuarios 
                        <a href="{{ url_for('main.manage_users') }}">Manage Users</a>-->
                    </nav>
                    
                    <h3>Dashboard</h3>
                    <p>Visualiza todas las incidencias en un solo lugar.</p>
                    <a href="{{ url_for('main.dashboard') }}" class="button btn-dashboard">Dashboard</a>
                </div>
                <!-- Caja de herramienta para registrar incidencias -->
                <div class="tool-box">
                    <h3>Registrar Incidencia</h3>
                    <p>Registra nuevas incidencias de manera rápida y sencilla.</p>
                    <a href="{{ url_for('main.register_incident') }}" class="button btn-register-incident">Registrar Incidencia</a>
                </div>
                <!-- Caja de herramienta para KPIs -->
                <div class="tool-box">
                    <h3>KPIs</h3>
                    <p>Analiza las incidencias a través de nuestras herramientas de KPIs.</p>
                    <a href="{{ url_for('main.kpis') }}" class="button btn-kpis">KPIs</a>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

app/templates/manage_users.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Manage Users</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
</head>
<body>
    <div class="container">
        <h1>Manage Users</h1>
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Username</th>
                    <th>Email</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for user in users %}
                <tr>
                    <td>{{ user.id }}</td>
                    <td>{{ user.username }}</td>
                    <td>{{ user.email }}</td>
                    <td>
                        <form method="POST" action="{{ url_for('main.manage_users') }}" style="display:inline;">
                            <input type="hidden" name="delete_user_id" value="{{ user.id }}">
                            <button type="submit">Delete</button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</body>
</html>